---
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    container_name: keycloak
    restart: always
    networks:
      - default
    ports:
      - "8080:8080"
    env_file: ".env"
    command: start-dev
